# Generated by Django 5.0.2 on 2024-03-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Session_Year',
        ),
    ]
