# Generated by Django 5.0.2 on 2024-03-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_session_session_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='session_id',
            new_name='session_year_id',
        ),
    ]
